apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
  namespace: fdcrpa
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    zalando:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    foo: zalando  # dbname: owner
  postgresql:
    version: "16"
  enableLogicalBackup: true
  logicalBackupSchedule: "30 0 * * *" # every day at 00:30
  # connectionPooler:
  #   numberOfInstances: 1