image:
  registry: ghcr.io
  repository: zalando/postgres-operator
  tag: v1.14.0
  pullPolicy: "IfNotPresent"

# general configuration parameters
configGeneral:
  # Spilo docker image
  docker_image: ghcr.io/zalando/spilo-17:4.0-p2

# configure K8s cron job managed by the operator
configLogicalBackup:
  # image for pods of the logical backup job (example runs pg_dumpall)
  logical_backup_docker_image: "ghcr.io/zalando/postgres-operator/logical-backup:v1.13.0"
  # S3 endpoint url when not using AWS
  logical_backup_s3_endpoint: "http://myrls-minio.default.svc.cluster.local:9000"
  # S3 Access Key ID
  logical_backup_s3_access_key_id: "admin"
  # S3 bucket to store backup results
  logical_backup_s3_bucket: "main"
  # S3 Secret Access Key
  logical_backup_s3_secret_access_key: "fdcrpafdcrpa"
  # backup schedule in the cron format
  logical_backup_schedule: "30 00 * * *" # daily at 00:30
  # S3 server side encryption
  logical_backup_s3_sse: ""

# configure connection pooler deployment created by the operator
configConnectionPooler:
  # docker image
  connection_pooler_image: "registry.opensource.zalan.do/acid/pgbouncer:master-32"


podServiceAccount:
  # The name of the ServiceAccount to be used by postgres cluster pods
  # If not set a name is generated using the fullname template and "-pod" suffix
  name: "postgres-pod"

configKubernetes:
  # operator watches for postgres objects in the given namespace
  watched_namespace: "fdcrpa"
  # role binding definition as JSON/YAML string to be used by pod service account
  pod_service_account_role_binding_definition: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: postgres-pod
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: postgres-pod
    subjects:
    - kind: ServiceAccount
      name: postgres-pod

# configure resource requests for the Postgres pods
configPostgresPodResources:
  # CPU limits for the postgres containers
  default_cpu_limit: "1"
  # CPU request value for the postgres containers
  default_cpu_request: 100m
  # memory limits for the postgres containers
  default_memory_limit: 500Mi
  # memory request value for the postgres containers
  default_memory_request: 100Mi