# general configuration parameters
configGeneral:
  # Spilo docker image
  docker_image: ghcr.io/zalando/spilo-17:4.0-p2

# configure K8s cron job managed by the operator
configLogicalBackup:
  # image for pods of the logical backup job (example runs pg_dumpall)
  logical_backup_docker_image: "ghcr.io/zalando/postgres-operator/logical-backup:v1.13.0"
  # S3 endpoint url when not using AWS
  logical_backup_s3_endpoint: "http://myrls-minio.default.svc.cluster.local:9000"
  # S3 Access Key ID
  logical_backup_s3_access_key_id: "admin"
  # S3 bucket to store backup results
  logical_backup_s3_bucket: "main"
  # S3 Secret Access Key
  logical_backup_s3_secret_access_key: "abc123abc123"
  # backup schedule in the cron format
  logical_backup_schedule: "30 00 * * *" # daily at 00:30
  # S3 server side encryption
  logical_backup_s3_sse: ""

# configure connection pooler deployment created by the operator
configConnectionPooler:
  # docker image
  connection_pooler_image: "registry.opensource.zalan.do/acid/pgbouncer:master-32"

configKubernetes:
  # operator watches for postgres objects in the given namespace
  watched_namespace: "default"

# configure resource requests for the Postgres pods
configPostgresPodResources:
  # CPU limits for the postgres containers
  default_cpu_limit: "1"
  # CPU request value for the postgres containers
  default_cpu_request: 100m
  # memory limits for the postgres containers
  default_memory_limit: 500Mi
  # memory request value for the postgres containers
  default_memory_request: 100Mi